# Student Score Data Processing App

## Introduction

This project loads a raw student score dataset from a CSV file,
cleans the data using Python functions, and processes the
cleaned scores using NumPy.

The project uses a virtual environment and runs in a Jupyter Notebook.

In [1]:
import numpy as np
import pandas as pd

from src.cleaning import load_data, clean_data, get_scores

## 1. Loading the Raw Dataset

The dataset contains student names, scores, and ages.
The CSV file intentionally contains some missing and invalid values
so that the cleaning process can be demonstrated.

In [2]:
data = load_data("data/students.csv")

data

       name  score  age
0     Abebe   85.0   20
1      Sara   92.0   21
2      Mimi   78.0   19
3      Dani    NaN   20
4      Liya  105.0   22
5  Kalkidan   88.0   21

## 2. Data Cleaning

The data is cleaned using functions from `cleaning.py`.

Missing scores are removed, and scores outside the valid range
of 0 to 100 are also removed.

In [5]:
cleaned_data = clean_data(data)

cleaned_data

       name  score  age
0     Abebe   85.0   20
1      Sara   92.0   21
2      Mimi   78.0   19
5  Kalkidan   88.0   21

## 3. Processing Data with NumPy

The cleaned scores are converted into a NumPy array.
NumPy is then used to calculate basic statistics.

In [6]:
scores = get_scores(cleaned_data)

print("Scores:", scores)

Scores: [85. 92. 78. 88.]

In [7]:
average_score = np.mean(scores)

print("Average score:", average_score)

highest_score = np.max(scores)
lowest_score = np.min(scores)

print("Highest score:", highest_score)
print("Lowest score:", lowest_score)


total_score = np.sum(scores)

print("Total score:", total_score)
passed_students = scores >= 50

pass_rate = np.mean(passed_students) * 100

print("Pass rate:", pass_rate, "%")

Average score: 85.75
Highest score: 92.0
Lowest score: 78.0
Total score: 343.0
Pass rate: 100.0 %

## 4. Final Results

The cleaned dataset contains only valid student scores.

The NumPy calculations show the average, highest score,
lowest score, total score, and overall pass rate.

In [ ]:
print("===== STUDENT SCORE REPORT =====")
print("Number of valid students:", len(scores))
print("Average score:", average_score)
print("Highest score:", highest_score)
print("Lowest score:", lowest_score)
print("Total score:", total_score)
print("Pass rate:", pass_rate, "%")

## 5. Conclusion

This project demonstrated a simple data-processing workflow.

The raw CSV dataset was loaded using Pandas, cleaned using
Python functions, and processed using NumPy.

The project also demonstrates how a virtual environment and
Jupyter Notebook can be used to organize and run a Python
data-processing application.